/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.deleteforms;

import inn.ambala.databaseconnection.admin.CompanyInfoTransactionCurd;
import inn.ambala.databaseconnection.userforms.addforms.LaundryAddCrud;
import inn.ambala.databaseconnection.userforms.addforms.OthersAddCrud;
import inn.ambala.databaseconnection.userforms.addforms.RestaurantAddCrud;
import inn.ambala.databaseconnection.userforms.addforms.ServicesMiniCrud;
import inn.ambala.databaseconnection.userforms.checkout.PayAboutCrud;
import inn.ambala.databaseconnection.userforms.checkout.PaymentCrud;
import inn.ambala.databaseconnection.userforms.conference.AmountDetailsCrud;
import inn.ambala.databaseconnection.userforms.conference.BookingDetailsCrud;
import inn.ambala.databaseconnection.userforms.conference.PaymentDetailsCrud;
import inn.ambala.databaseconnection.userforms.forms.UserInfoCrud;
import inn.ambala.databaseconnection.userforms.forms.UserOthersInfoCrud;
import inn.ambala.databaseconnection.userforms.forms.UserRoomInfoCrud;
import javax.swing.JOptionPane;

/**
 *
 * @author REZA
 */
public class Delete extends javax.swing.JPanel {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
    }
    
    private void deleteButtonPressed(){
        int cheak = 0;
        String mrNo = mrNoTF.getText();
        cheak += UserRoomInfoCrud.deleteUsingMR(mrNo);
        cheak +=UserOthersInfoCrud.deleteUsingMR(mrNo);
        cheak +=UserInfoCrud.deleteUsingMR(mrNo);
        cheak +=PaymentDetailsCrud.deleteUsingMR(mrNo);
        cheak +=AmountDetailsCrud.deleteUsingMR(mrNo);
        cheak +=BookingDetailsCrud.deleteUsingMR(mrNo);
        cheak +=PayAboutCrud.deleteUsingMR(mrNo);
        cheak +=PaymentCrud.deleteUsingMR(mrNo);
        cheak +=ServicesMiniCrud.deleteUsingMR(mrNo);
        cheak +=RestaurantAddCrud.deleteUsingMR(mrNo);
        cheak +=OthersAddCrud.deleteUsingMR(mrNo);
        cheak +=LaundryAddCrud.deleteUsingMR(mrNo);
        cheak +=CompanyInfoTransactionCurd.deleteUsingMR(mrNo);
        
        if(cheak > 0 ){
            mrNoTF.setText("");
            JOptionPane.showMessageDialog(null, "Successfully Deleted All Data Of MR-"+mrNo);
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid MR Number. No Data Found for Delete");
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mrNoTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Delete Data");

        jLabel2.setText("MR No :");

        mrNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrNoTFActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(mrNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mrNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mrNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrNoTFActionPerformed
        deleteButtonPressed();
    }//GEN-LAST:event_mrNoTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        deleteButtonPressed();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mrNoTF;
    // End of variables declaration//GEN-END:variables
}
