/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.adminforms.addforms;

import inn.ambala.admin.model.CompanyInfoModel;
import inn.ambala.dashboard.adminforms.CompanyInfo;
import inn.ambala.databaseconnection.admin.CompanyInfoCrud;
import inn.ambala.resources.Resources;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author REZA
 */
public class CompanyInfoAdd extends javax.swing.JFrame {

    /**
     * Creates new form CompanyInfoAdd
     */
    public CompanyInfoAdd() {
        initComponents();
        initExtraComponents();
    }

    private void initExtraComponents() {
        ImageIcon key = new ImageIcon(Resources.getPath() + "icon-01.jpg");
        Image image = key.getImage();
        setIconImage(image);
        setTitle("Ambala Inn");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        balanceTF.setText("0");
        balanceTF.setEditable(false);
    }

    private void createButtonPressed() {
        if (companyCodeTF.getText().equals("") || companyNameTF.getText().equals("") || balanceTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Company Code,Company Name and Balance");
        } else {
            int companyId = 0; // database auto increment will handle it
            try{
                int companyCode = Integer.valueOf(companyCodeTF.getText());
                String companyName = companyNameTF.getText();
                String contactPerson = contactPersonTF.getText();
                String phone = phoneTF.getText();
                String email = emailTF.getText();
                String address = addressTF.getText();
                String mobile = mobileTF.getText();
                int balance = Integer.valueOf(balanceTF.getText());

                CompanyInfoCrud.addCompanyInfo(new CompanyInfoModel(companyId, companyCode, companyName, contactPerson, phone, email, address, mobile, balance));
                CompanyInfo.refreshTable();
                dispose();

                JOptionPane.showMessageDialog(null, "Company Info Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Company Code and Balance is Contains Digits Only");
            }
        }
    }

    private void createAnotherButtonPressed() {
        if (companyCodeTF.getText().equals("") || companyNameTF.getText().equals("") || balanceTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Company Code,Company Name and Balance");
        } else {
            int companyId = 0; // database auto increment will handle it
            try{
                int companyCode = Integer.valueOf(companyCodeTF.getText());
                String companyName = companyNameTF.getText();
                String contactPerson = contactPersonTF.getText();
                String phone = phoneTF.getText();
                String email = emailTF.getText();
                String address = addressTF.getText();
                String mobile = mobileTF.getText();
                int balance = Integer.valueOf(balanceTF.getText());

                CompanyInfoCrud.addCompanyInfo(new CompanyInfoModel(companyId, companyCode, companyName, contactPerson, phone, email, address, mobile, balance));

                companyCodeTF.setText("");
                companyNameTF.setText("");
                contactPersonTF.setText("");
                phoneTF.setText("");
                emailTF.setText("");
                addressTF.setText("");
                mobileTF.setText("");
                balanceTF.setText("");

                CompanyInfo.refreshTable();

                JOptionPane.showMessageDialog(null, "Company Info Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Company Code and Balance is Contains Digits Only");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyInfoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        companyCodeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        companyNameTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contactPersonTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mobileTF = new javax.swing.JTextField();
        balanceTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        createAnotherButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        companyInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        companyInfoLabel.setText("Company Info");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Company Code");

        companyCodeTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        companyCodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyCodeTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Company Name");

        companyNameTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        companyNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameTFActionPerformed(evt);
            }
        });

        phoneTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Phone");

        contactPersonTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        contactPersonTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactPersonTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Contact Person");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Address");

        addressTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        emailTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Balance");

        mobileTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mobileTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTFActionPerformed(evt);
            }
        });

        balanceTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        balanceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceTFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Mobile");

        createButton.setBackground(new java.awt.Color(59, 180, 74));
        createButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        createAnotherButton.setBackground(new java.awt.Color(236, 0, 138));
        createAnotherButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createAnotherButton.setForeground(new java.awt.Color(255, 255, 255));
        createAnotherButton.setText("Create & Another");
        createAnotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAnotherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(companyInfoLabel)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(contactPersonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(companyCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(120, 120, 120))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(121, 121, 121)))
                            .addComponent(phoneTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyNameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createAnotherButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companyNameTF)
                    .addComponent(companyCodeTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneTF)
                    .addComponent(contactPersonTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailTF)
                    .addComponent(addressTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(balanceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(mobileTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(createAnotherButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAnotherButtonActionPerformed
        createAnotherButtonPressed();
    }//GEN-LAST:event_createAnotherButtonActionPerformed

    private void companyNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_companyNameTFActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_createButtonActionPerformed

    private void balanceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_balanceTFActionPerformed

    private void mobileTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_mobileTFActionPerformed

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_addressTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_emailTFActionPerformed

    private void phoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_phoneTFActionPerformed

    private void contactPersonTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactPersonTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_contactPersonTFActionPerformed

    private void companyCodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyCodeTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_companyCodeTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyInfoAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField balanceTF;
    private javax.swing.JTextField companyCodeTF;
    private javax.swing.JLabel companyInfoLabel;
    private javax.swing.JTextField companyNameTF;
    private javax.swing.JTextField contactPersonTF;
    private javax.swing.JButton createAnotherButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JTextField phoneTF;
    // End of variables declaration//GEN-END:variables
}
