/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.adminforms.addforms;

import inn.ambala.admin.model.CompanyInfoModel;
import inn.ambala.admin.model.CompanyInfoTransactionModel;
import inn.ambala.dashboard.adminforms.CompanyInfo;
import inn.ambala.dashboard.adminforms.reports.print.CompanyInfoDepositePrint;
import inn.ambala.databaseconnection.admin.CompanyInfoCrud;
import inn.ambala.databaseconnection.admin.CompanyInfoTransactionCurd;
import inn.ambala.keypicker.KeyGenerator;
import inn.ambala.resources.Resources;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author REZA
 */
public class CompanyInfoDeposite extends javax.swing.JFrame {

    CompanyInfoModel companyInfoModel = null;
    /**
     * Creates new form CompanyInfoDeposite
     */
    public CompanyInfoDeposite() {
        initComponents();
        initExtraComponents();
    }
    
    public CompanyInfoDeposite(CompanyInfoModel companyInfoModel) {
        initComponents();
        initExtraComponents();
        this.companyInfoModel = companyInfoModel;

        companyCodeLabel.setText("" + companyInfoModel.getCompanyCode());
        companyNameLabel.setText(companyInfoModel.getCompanyName());
        contactPersonLabel.setText(companyInfoModel.getContactPerson());
        phoneLabel.setText(companyInfoModel.getPhone());
        emailLabel.setText(companyInfoModel.getEmail());
        addressLabel.setText(companyInfoModel.getAddress());
        mobileLabel.setText(companyInfoModel.getMobile());
        balanceLabel.setText("" + companyInfoModel.getBalance());

    }

    private void initExtraComponents() {
        ImageIcon key = new ImageIcon(Resources.getPath() + "icon-01.jpg");
        Image image = key.getImage();
        setIconImage(image);
        setTitle("Ambala Inn");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }
    
    private void depositeButtonPressed(){
        
        if (depositeTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill the field");
        } else {
            try{
                int amount = Integer.valueOf(depositeTF.getText());
                int result = 0;
                KeyGenerator key = new KeyGenerator();
                String id = key.getKey();
                int companyCode = Integer.valueOf(companyCodeLabel.getText());
                String companyName = companyNameLabel.getText();
                String Status = "Pay";
                String reason = "Company Deposite";
                String mrNo = "None";
                Date date = new Date();

                result = CompanyInfoCrud.updateCompanyBalanceByCode(companyCode, amount);
                CompanyInfoTransactionModel citm = new CompanyInfoTransactionModel(id, companyCode, companyName, amount, Status, reason, mrNo, date);
                CompanyInfoTransactionCurd.addTransaction(citm);
                CompanyInfo.refreshTable(); 
                dispose();
                new CompanyInfoDepositePrint(companyInfoModel, amount).setVisible(true);
                if (result == 1) {
                    JOptionPane.showMessageDialog(null, "Deposite Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Not Successfully Deposite");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Digits Only");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyInfoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        depositeButton = new javax.swing.JButton();
        companyCodeLabel = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        contactPersonLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        depositeTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        companyInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        companyInfoLabel.setText("Company Info");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Company Code :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Company Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Contact Person :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Phone :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Address :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Email :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Current Balance :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Mobile :");

        depositeButton.setBackground(new java.awt.Color(59, 180, 74));
        depositeButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        depositeButton.setForeground(new java.awt.Color(255, 255, 255));
        depositeButton.setText("Deposit");
        depositeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositeButtonActionPerformed(evt);
            }
        });

        companyCodeLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        companyCodeLabel.setText("Code");

        companyNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        companyNameLabel.setText("Name");

        contactPersonLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        contactPersonLabel.setText("Contact Person");

        phoneLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        phoneLabel.setText("Phone");

        emailLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        emailLabel.setText("Email");

        addressLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        addressLabel.setText("Address");

        mobileLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        mobileLabel.setText("Email");

        balanceLabel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        balanceLabel.setText("Balance");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Deposit Amount :");

        depositeTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        depositeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositeTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(companyCodeLabel)
                    .addComponent(contactPersonLabel)
                    .addComponent(emailLabel)
                    .addComponent(mobileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(balanceLabel)
                    .addComponent(addressLabel)
                    .addComponent(phoneLabel)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(companyNameLabel)
                    .addComponent(jLabel8))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(companyInfoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(depositeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(depositeButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyCodeLabel)
                    .addComponent(companyNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactPersonLabel)
                    .addComponent(phoneLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(addressLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileLabel)
                    .addComponent(balanceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(depositeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositeButtonActionPerformed
        depositeButtonPressed();
    }//GEN-LAST:event_depositeButtonActionPerformed

    private void depositeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositeTFActionPerformed
        depositeButtonPressed();
    }//GEN-LAST:event_depositeTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyInfoDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyInfoDeposite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel companyCodeLabel;
    private javax.swing.JLabel companyInfoLabel;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JLabel contactPersonLabel;
    private javax.swing.JButton depositeButton;
    private javax.swing.JTextField depositeTF;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JLabel phoneLabel;
    // End of variables declaration//GEN-END:variables
}
