/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.adminforms.addforms;

import inn.ambala.admin.model.LaundryModel;
import inn.ambala.dashboard.adminforms.Laundry;
import inn.ambala.databaseconnection.admin.LaundryCrud;
import inn.ambala.resources.Resources;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author REZA
 */
public class LaundryAdd extends javax.swing.JFrame {

    /**
     * Creates new form LaundryAdd
     */
    public LaundryAdd() {
        initComponents();
        initExtraComponents();
    }
    
    private void initExtraComponents() {
        ImageIcon key = new ImageIcon(Resources.getPath() + "icon-01.jpg");
        Image image = key.getImage();
        setIconImage(image);
        setTitle("Ambala Inn");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private void createButtonPressed() {
        if (laundryCodeTF.getText().equals("") || laundryTypeTF.getText().equals("") || clothTypeTF.getText().equals("") || priceTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill up this form carefully");
        } else {
            int laundryId = 0; // database auto increment will handle it
            try{
                int laundryCode = Integer.valueOf(laundryCodeTF.getText());
                String laundryType = laundryTypeTF.getText();
                String clothType = clothTypeTF.getText();
                int price = Integer.valueOf(priceTF.getText());

                LaundryCrud.addLaundry(new LaundryModel(laundryId, laundryCode, laundryType, clothType, price));
                Laundry.refreshTable();

                dispose();

                JOptionPane.showMessageDialog(null, "Laundry Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Digits Only on Laundry Code and Price");
            }
        }

    }

    private void createAnotherButtonPressed() {
        if (laundryCodeTF.getText().equals("") || laundryTypeTF.getText().equals("") || clothTypeTF.getText().equals("") || priceTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill up this form carefully");
        } else {
            int laundryId = 0; // database auto increment will handle it
            try{
                int laundryCode = Integer.valueOf(laundryCodeTF.getText());
                String laundryType = laundryTypeTF.getText();
                String clothType = clothTypeTF.getText();
                int price = Integer.valueOf(priceTF.getText());

                LaundryCrud.addLaundry(new LaundryModel(laundryId, laundryCode, laundryType, clothType, price));

                laundryCodeTF.setText("");
                laundryTypeTF.setText("");
                clothTypeTF.setText("");
                priceTF.setText("");

                Laundry.refreshTable();

                JOptionPane.showMessageDialog(null, "Laundry Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Digits Only on Laundry Code and Price");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laundryLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        clothTypeTF = new javax.swing.JTextField();
        laundryCodeTF = new javax.swing.JTextField();
        createAnotherButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        laundryTypeTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laundryLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        laundryLabel.setText("Laundry");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Price :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Cloth Type :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Laundry Code :");

        priceTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        priceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTFActionPerformed(evt);
            }
        });

        clothTypeTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        clothTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothTypeTFActionPerformed(evt);
            }
        });

        laundryCodeTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        laundryCodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laundryCodeTFActionPerformed(evt);
            }
        });

        createAnotherButton.setBackground(new java.awt.Color(236, 0, 138));
        createAnotherButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createAnotherButton.setForeground(new java.awt.Color(255, 255, 255));
        createAnotherButton.setText("Create & Another");
        createAnotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAnotherButtonActionPerformed(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(59, 180, 74));
        createButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        laundryTypeTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        laundryTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laundryTypeTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Laundry Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createAnotherButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(laundryLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(laundryCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(laundryTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clothTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laundryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laundryCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laundryTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAnotherButton)
                    .addComponent(createButton))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAnotherButtonActionPerformed
        createAnotherButtonPressed();
    }//GEN-LAST:event_createAnotherButtonActionPerformed

    private void laundryTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laundryTypeTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_laundryTypeTFActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_createButtonActionPerformed

    private void priceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_priceTFActionPerformed

    private void clothTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothTypeTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_clothTypeTFActionPerformed

    private void laundryCodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laundryCodeTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_laundryCodeTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaundryAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaundryAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaundryAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaundryAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaundryAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clothTypeTF;
    private javax.swing.JButton createAnotherButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField laundryCodeTF;
    private javax.swing.JLabel laundryLabel;
    private javax.swing.JTextField laundryTypeTF;
    private javax.swing.JTextField priceTF;
    // End of variables declaration//GEN-END:variables
}
