/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.adminforms.addforms;

import inn.ambala.admin.model.RestaurantModel;
import inn.ambala.admin.model.RoomDetailsModel;
import inn.ambala.dashboard.adminforms.Restaurant;
import inn.ambala.dashboard.adminforms.RoomDetails;
import inn.ambala.databaseconnection.admin.RestaurantCrud;
import inn.ambala.databaseconnection.admin.RoomDetailsCrud;
import inn.ambala.resources.Resources;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author REZA
 */
public class RestaurantAdd extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantAdd
     */
    public RestaurantAdd() {
        initComponents();
        initExtraComponents();
    }
    
    private void initExtraComponents(){
        ImageIcon key = new ImageIcon(Resources.getPath() + "icon-01.jpg");
        Image image = key.getImage();
        setIconImage(image);
        setTitle("Ambala Inn");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    private void createButtonPressed() {
        if (itemCodeTF.getText().equals("") || itemPriceTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill up this form carefully");
        } else {
            int restaurantId = 0; // database auto increment will handle it
            try{
                int itemCode = Integer.valueOf(itemCodeTF.getText());
                String itemName = itemNameTF.getText();
                String foodType = foodTypeTF.getText();
                int itemPrice = Integer.valueOf(itemPriceTF.getText());

                RestaurantCrud.addItem(new RestaurantModel(restaurantId, itemCode, itemName, foodType, itemPrice));
                Restaurant.refreshTable();
                dispose();

                JOptionPane.showMessageDialog(null, "Item Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Digits Only on ID and Price");
            }
        }

    }

    private void createAnotherButtonPressed() {
        if (itemCodeTF.getText().equals("") || itemPriceTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill up this form carefully");
        } else {
            int restaurantId = 0; // database auto increment will handle it
            try{
                int itemCode = Integer.valueOf(itemCodeTF.getText());
                String itemName = itemNameTF.getText();
                String foodType = foodTypeTF.getText();
                int itemPrice = Integer.valueOf(itemPriceTF.getText());

                RestaurantCrud.addItem(new RestaurantModel(restaurantId, itemCode, itemName, foodType, itemPrice));

                itemCodeTF.setText("");
                itemNameTF.setText("");
                foodTypeTF.setText("");
                itemPriceTF.setText("");

                Restaurant.refreshTable();

                JOptionPane.showMessageDialog(null, "Item Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Digits Only on ID and Price");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurantLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itemPriceTF = new javax.swing.JTextField();
        foodTypeTF = new javax.swing.JTextField();
        itemNameTF = new javax.swing.JTextField();
        itemCodeTF = new javax.swing.JTextField();
        createAnotherButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        restaurantLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        restaurantLabel.setText("Restaurant");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Item Price :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Food Type :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Item Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Item Code :");

        itemPriceTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        itemPriceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPriceTFActionPerformed(evt);
            }
        });

        foodTypeTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        foodTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodTypeTFActionPerformed(evt);
            }
        });

        itemNameTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        itemNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTFActionPerformed(evt);
            }
        });

        itemCodeTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        itemCodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTFActionPerformed(evt);
            }
        });

        createAnotherButton.setBackground(new java.awt.Color(236, 0, 138));
        createAnotherButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createAnotherButton.setForeground(new java.awt.Color(255, 255, 255));
        createAnotherButton.setText("Create & Another");
        createAnotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAnotherButtonActionPerformed(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(59, 180, 74));
        createButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createAnotherButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(restaurantLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAnotherButton)
                    .addComponent(createButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAnotherButtonActionPerformed
        createAnotherButtonPressed();
    }//GEN-LAST:event_createAnotherButtonActionPerformed

    private void itemPriceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPriceTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_itemPriceTFActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_createButtonActionPerformed

    private void foodTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodTypeTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_foodTypeTFActionPerformed

    private void itemNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_itemNameTFActionPerformed

    private void itemCodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTFActionPerformed
        createButtonPressed();
    }//GEN-LAST:event_itemCodeTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAnotherButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField foodTypeTF;
    private javax.swing.JTextField itemCodeTF;
    private javax.swing.JTextField itemNameTF;
    private javax.swing.JTextField itemPriceTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel restaurantLabel;
    // End of variables declaration//GEN-END:variables
}
