/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.userforms.addforms;

import inn.ambala.dashboard.userforms.Others;
import inn.ambala.databaseconnection.userforms.addforms.OthersAddCrud;
import inn.ambala.keypicker.KeyGenerator;
import inn.ambala.resources.Resources;
import inn.ambala.user.model.OthersModel;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author REZA
 */
public class OthersAdd extends javax.swing.JFrame {
    
    /**
     * Creates new form OthersAdd
     */
    public OthersAdd() {
        initComponents();
        initExtraComponents();
    }
    
    public OthersAdd(int roomNo, String mrNo) {
        initComponents();
        initExtraComponents();
        roomNoTF.setText(roomNo+"");
        mrNoTF.setText(mrNo);
    }
    
    private void initExtraComponents() {
        ImageIcon key = new ImageIcon(Resources.getPath() + "icon-01.jpg");
        Image image = key.getImage();
        setIconImage(image);
        setTitle("Ambala Inn");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        roomNoTF.setEditable(false);
        mrNoTF.setEditable(false);
        roomNoTF.setEnabled(false);
        mrNoTF.setEnabled(false);
    }
    
    private void addButtonPressed(){
        if(roomNoTF.getText().equals("") || mrNoTF.getText().equals("") || descriptionTF.getText().equals("") || amountTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill All Details");
        }
        else{
            try{
                int roomNo = Integer.valueOf(roomNoTF.getText());
                String mrNo =  mrNoTF.getText();
                String description = descriptionTF.getText();
                int amount = Integer.valueOf(amountTF.getText());
                KeyGenerator key = new KeyGenerator();
                String othersNo = key.getKey();
                Date date = new Date();

                OthersModel othersModel = new OthersModel(othersNo, mrNo, roomNo, description, amount, date);
                OthersAddCrud.addOthers(othersModel);

                Others.refreshTable(mrNo);
                dispose();
                JOptionPane.showMessageDialog(null, "Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Enter Correct Information");
            }
        }
        
    }
    
    
    private void addAnotherButtonPressed(){
        if(roomNoTF.getText().equals("") || mrNoTF.getText().equals("") || descriptionTF.getText().equals("") || amountTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill All Details");
        }
        else{
            try{
                int roomNo = Integer.valueOf(roomNoTF.getText());
                String mrNo =  mrNoTF.getText();
                String description = descriptionTF.getText();
                int amount = Integer.valueOf(amountTF.getText());
                KeyGenerator key = new KeyGenerator();
                String othersNo = key.getKey();
                Date date = new Date();

                OthersModel othersModel = new OthersModel(othersNo, mrNo, roomNo, description, amount, date);
                OthersAddCrud.addOthers(othersModel);

                descriptionTF.setText("");
                amountTF.setText("");
                Others.refreshTable(mrNo);
                JOptionPane.showMessageDialog(null, "Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Enter Correct Information");
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        othersLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        descriptionTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        addAnotherButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        roomNoTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mrNoTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        othersLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        othersLabel.setText("Others");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Description :");

        descriptionTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        descriptionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Amount :");

        amountTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });

        addAnotherButton.setBackground(new java.awt.Color(236, 0, 138));
        addAnotherButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addAnotherButton.setForeground(new java.awt.Color(255, 255, 255));
        addAnotherButton.setText("Add & Another");
        addAnotherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnotherButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(59, 180, 74));
        addButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Room No :");

        roomNoTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        roomNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNoTFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("MR No :");

        mrNoTF.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mrNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrNoTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountTF)
                                    .addComponent(descriptionTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mrNoTF)
                                    .addComponent(roomNoTF))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(othersLabel)
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addAnotherButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(othersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAnotherButton)
                    .addComponent(addButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTFActionPerformed
        addButtonPressed();
    }//GEN-LAST:event_descriptionTFActionPerformed

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        addButtonPressed();
    }//GEN-LAST:event_amountTFActionPerformed

    private void addAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnotherButtonActionPerformed
        addAnotherButtonPressed();
    }//GEN-LAST:event_addAnotherButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addButtonPressed();
    }//GEN-LAST:event_addButtonActionPerformed

    private void roomNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNoTFActionPerformed

    private void mrNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrNoTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OthersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OthersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OthersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OthersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OthersAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnotherButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountTF;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mrNoTF;
    private javax.swing.JLabel othersLabel;
    private javax.swing.JTextField roomNoTF;
    // End of variables declaration//GEN-END:variables
}
