/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.adminforms;

import inn.ambala.dashboard.adminforms.reports.AdvanceBookingReport;
import inn.ambala.dashboard.adminforms.reports.CompanyInfoReport;
import inn.ambala.dashboard.adminforms.reports.ConferenceBookingsReport;
import inn.ambala.dashboard.adminforms.reports.CurrentConferenceBookingReport;
import inn.ambala.dashboard.adminforms.reports.DailyGuestReport;
import inn.ambala.dashboard.adminforms.reports.GuestAddressReport;
import inn.ambala.dashboard.adminforms.reports.GuestDepositeReport;
import inn.ambala.dashboard.adminforms.reports.GuestDueReport;
import inn.ambala.dashboard.adminforms.reports.LaundryInfoReport;
import inn.ambala.dashboard.adminforms.reports.RestaurantInfoReport;
import inn.ambala.dashboard.adminforms.reports.TotalBillReport;
import inn.ambala.dashboard.adminforms.reports.VacantRoomReport;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import inn.ambala.reports.controller.VacaentRoomsJR;

/**
 *
 * @author REZA
 */
public class Report extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromDC = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        toDC = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        dailyGuestStatementButton = new javax.swing.JButton();
        advanceBookingButton = new javax.swing.JButton();
        guestAddressButton = new javax.swing.JButton();
        guestDueListButton = new javax.swing.JButton();
        totalBillButton = new javax.swing.JButton();
        laundryInfoButton = new javax.swing.JButton();
        restaurantInfoButton = new javax.swing.JButton();
        guestDepositeButton = new javax.swing.JButton();
        companyInfoButton = new javax.swing.JButton();
        vacantRoomsButton = new javax.swing.JButton();
        conferenceBookingButton = new javax.swing.JButton();
        conferenceCurrentBookingButton = new javax.swing.JButton();

        reportLabel.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        reportLabel.setText("Report");

        jLabel2.setText("From :");

        fromDC.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("To :");

        toDC.setDateFormatString("yyyy-MM-dd");

        dailyGuestStatementButton.setText("Daily Guest Statement");
        dailyGuestStatementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyGuestStatementButtonActionPerformed(evt);
            }
        });

        advanceBookingButton.setText("Advance Booking");
        advanceBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanceBookingButtonActionPerformed(evt);
            }
        });

        guestAddressButton.setText("Guest Address");
        guestAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestAddressButtonActionPerformed(evt);
            }
        });

        guestDueListButton.setText("Guest Due List");
        guestDueListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestDueListButtonActionPerformed(evt);
            }
        });

        totalBillButton.setText("Total Bill");
        totalBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBillButtonActionPerformed(evt);
            }
        });

        laundryInfoButton.setText("Laundry Info");
        laundryInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laundryInfoButtonActionPerformed(evt);
            }
        });

        restaurantInfoButton.setText("Restaurant Info");
        restaurantInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantInfoButtonActionPerformed(evt);
            }
        });

        guestDepositeButton.setText("Guest Deposite");
        guestDepositeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestDepositeButtonActionPerformed(evt);
            }
        });

        companyInfoButton.setText("Company Info");
        companyInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyInfoButtonActionPerformed(evt);
            }
        });

        vacantRoomsButton.setText("Vacant Rooms");
        vacantRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacantRoomsButtonActionPerformed(evt);
            }
        });

        conferenceBookingButton.setText("Conference Bookings");
        conferenceBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferenceBookingButtonActionPerformed(evt);
            }
        });

        conferenceCurrentBookingButton.setText("Conference Current Booking");
        conferenceCurrentBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferenceCurrentBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fromDC, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(advanceBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guestAddressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guestDepositeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guestDueListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dailyGuestStatementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conferenceCurrentBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(toDC, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(conferenceBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(restaurantInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalBillButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vacantRoomsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(companyInfoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laundryInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportLabel)
                .addGap(326, 326, 326))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(fromDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dailyGuestStatementButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(advanceBookingButton)
                                .addGap(18, 18, 18)
                                .addComponent(guestAddressButton)
                                .addGap(18, 18, 18)
                                .addComponent(guestDepositeButton)))
                        .addGap(18, 18, 18)
                        .addComponent(guestDueListButton)
                        .addGap(18, 18, 18)
                        .addComponent(conferenceCurrentBookingButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reportLabel)
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addComponent(totalBillButton)
                        .addGap(18, 18, 18)
                        .addComponent(vacantRoomsButton)
                        .addGap(18, 18, 18)
                        .addComponent(companyInfoButton)
                        .addGap(18, 18, 18)
                        .addComponent(restaurantInfoButton)
                        .addGap(18, 18, 18)
                        .addComponent(laundryInfoButton)
                        .addGap(18, 18, 18)
                        .addComponent(conferenceBookingButton)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void laundryInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laundryInfoButtonActionPerformed
        new LaundryInfoReport().setVisible(true);
    }//GEN-LAST:event_laundryInfoButtonActionPerformed

    private void advanceBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanceBookingButtonActionPerformed
        new AdvanceBookingReport().setVisible(true);
    }//GEN-LAST:event_advanceBookingButtonActionPerformed

    private void companyInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyInfoButtonActionPerformed
        new CompanyInfoReport().setVisible(true);
    }//GEN-LAST:event_companyInfoButtonActionPerformed

    private void restaurantInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantInfoButtonActionPerformed
        new RestaurantInfoReport().setVisible(true);
    }//GEN-LAST:event_restaurantInfoButtonActionPerformed

    private void dailyGuestStatementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyGuestStatementButtonActionPerformed
        new DailyGuestReport().setVisible(true);
    }//GEN-LAST:event_dailyGuestStatementButtonActionPerformed

    private void vacantRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacantRoomsButtonActionPerformed
        new VacantRoomReport().setVisible(true);
    }//GEN-LAST:event_vacantRoomsButtonActionPerformed

    private void conferenceBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferenceBookingButtonActionPerformed
        if(fromDC.getDate() == null){
            JOptionPane.showMessageDialog(null, "Enter Date from");
        }
        else if(toDC.getDate() == null){
            JOptionPane.showMessageDialog(null, "Enter Date to");
        }
        else{
            Date from = fromDC.getDate();
            Date to = toDC.getDate();
            new ConferenceBookingsReport(from, to).setVisible(true);
        }
    }//GEN-LAST:event_conferenceBookingButtonActionPerformed

    private void guestAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestAddressButtonActionPerformed
        if(fromDC.getDate() == null){
            JOptionPane.showMessageDialog(null, "Enter Date from");
        }
        else if(toDC.getDate() == null){
            JOptionPane.showMessageDialog(null, "Enter Date to");
        }
        else{
            Date from = fromDC.getDate();
            Date to = toDC.getDate();
            new GuestAddressReport(from, to).setVisible(true);
        }
    }//GEN-LAST:event_guestAddressButtonActionPerformed

    private void guestDueListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestDueListButtonActionPerformed
        new GuestDueReport().setVisible(true);
    }//GEN-LAST:event_guestDueListButtonActionPerformed

    private void guestDepositeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestDepositeButtonActionPerformed
        new GuestDepositeReport().setVisible(true);
    }//GEN-LAST:event_guestDepositeButtonActionPerformed

    private void conferenceCurrentBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferenceCurrentBookingButtonActionPerformed
        new CurrentConferenceBookingReport().setVisible(true);
    }//GEN-LAST:event_conferenceCurrentBookingButtonActionPerformed

    private void totalBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBillButtonActionPerformed
        if(fromDC.getDate() == null){
            JOptionPane.showMessageDialog(null, "Enter Date from");
        }
        else if(toDC.getDate() == null){
            JOptionPane.showMessageDialog(null, "Enter Date to");
        }
        else{
            Date from = fromDC.getDate();
            Date to = toDC.getDate();
            new TotalBillReport(from, to).setVisible(true);
        }
    }//GEN-LAST:event_totalBillButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advanceBookingButton;
    private javax.swing.JButton companyInfoButton;
    private javax.swing.JButton conferenceBookingButton;
    private javax.swing.JButton conferenceCurrentBookingButton;
    private javax.swing.JButton dailyGuestStatementButton;
    private com.toedter.calendar.JDateChooser fromDC;
    private javax.swing.JButton guestAddressButton;
    private javax.swing.JButton guestDepositeButton;
    private javax.swing.JButton guestDueListButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton laundryInfoButton;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JButton restaurantInfoButton;
    private com.toedter.calendar.JDateChooser toDC;
    private javax.swing.JButton totalBillButton;
    private javax.swing.JButton vacantRoomsButton;
    // End of variables declaration//GEN-END:variables
}
