/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inn.ambala.dashboard.adminforms;

import inn.ambala.databaseconnection.users.UserAccessCrud;
import javax.swing.JOptionPane;

/**
 *
 * @author REZA
 */
public class Settings extends javax.swing.JPanel {
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }
    
    
    private void changePasswordButtonClicked(){
        if(userNameTF.getText().equals("") || oldPasswordPF.getText().equals("") || newPasswordPF.getText().equals("") || confirmPasswordPF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fill all the Fields");
        }
        else if(newPasswordPF.getText().length()<5){
            JOptionPane.showMessageDialog(null, "Password is too small");
        }
        else if(!newPasswordPF.getText().equals(confirmPasswordPF.getText())){
            JOptionPane.showMessageDialog(null, "New Password Didn't Match");
        }
        else{
            int result = UserAccessCrud.changeUserPassword(userNameTF.getText(), oldPasswordPF.getText(), newPasswordPF.getText());
            if(result > 0){
                userNameTF.setText("");
                oldPasswordPF.setText("");
                newPasswordPF.setText("");
                confirmPasswordPF.setText("");
                JOptionPane.showMessageDialog(null, "Password Changed Successfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Enter the Correct Infomation Carefully");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        changePasswordButton = new javax.swing.JButton();
        oldPasswordPF = new javax.swing.JPasswordField();
        newPasswordPF = new javax.swing.JPasswordField();
        confirmPasswordPF = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Settings");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Username :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Old Password :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("New Password :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Confirm Password :");

        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });

        changePasswordButton.setBackground(new java.awt.Color(59, 180, 74));
        changePasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordButton.setText("Change Password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        oldPasswordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordPFActionPerformed(evt);
            }
        });

        newPasswordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordPFActionPerformed(evt);
            }
        });

        confirmPasswordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePasswordButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameTF)
                                    .addComponent(oldPasswordPF)
                                    .addComponent(newPasswordPF, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(confirmPasswordPF))))))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(oldPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(confirmPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changePasswordButton)
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        changePasswordButtonClicked();
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void confirmPasswordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordPFActionPerformed
        changePasswordButtonClicked();
    }//GEN-LAST:event_confirmPasswordPFActionPerformed

    private void newPasswordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordPFActionPerformed
        changePasswordButtonClicked();
    }//GEN-LAST:event_newPasswordPFActionPerformed

    private void oldPasswordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordPFActionPerformed
        changePasswordButtonClicked();
    }//GEN-LAST:event_oldPasswordPFActionPerformed

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        changePasswordButtonClicked();
    }//GEN-LAST:event_userNameTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JPasswordField confirmPasswordPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newPasswordPF;
    private javax.swing.JPasswordField oldPasswordPF;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
